# Generated by Django 6.0 on 2026-01-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
