# Generated by Django 6.0 on 2026-01-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal_price',
            field=models.BooleanField(default=False),
        ),
    ]
