# Generated by Django 6.0 on 2026-01-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_is_deal_price'),
        ('pricing_monitor', '0003_csvimportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='csv_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_products', to='pricing_monitor.productcsvupload'),
        ),
    ]
