# Generated by Django 6.0 on 2026-01-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_csv_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='csv_upload',
        ),
    ]
