# Generated by Django 6.0 on 2026-01-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
