# Generated by Django 6.0 on 2026-01-21 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_monitor', '0003_csvimportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcsvupload',
            name='min_net_price_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Minimum Net Price percentage of MRP (e.g. 50 = 50%)', max_digits=5),
        ),
    ]
