# Generated by Django 6.0 on 2026-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_monitor', '0004_productcsvupload_min_net_price_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skippedpriceimport',
            name='min_price_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
