# Generated by Django 6.0 on 2026-01-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_csv_upload'),
        ('pricing_monitor', '0005_skippedpriceimport_min_price_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_products', to='pricing_monitor.productcsvupload')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
