# Generated by Django 6.0 on 2026-01-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_monitor', '0006_importedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcsvupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='csv_uploads/'),
        ),
    ]
