# Generated by Django 6.0.1 on 2026-01-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_monitor', '0007_alter_productcsvupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcsvupload',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcsvupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pricing_monitor/uploads/'),
        ),
    ]
