# Generated by Django 6.0.1 on 2026-01-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_monitor', '0008_productcsvupload_status_alter_productcsvupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcsvupload',
            name='min_net_price_percent',
        ),
    ]
