# Generated by Django 6.0.1 on 2026-01-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_monitor', '0009_remove_productcsvupload_min_net_price_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcsvupload',
            name='consider_price_validation',
            field=models.BooleanField(default=True, help_text='If unchecked, CSV prices will be imported without validation'),
        ),
    ]
