# Generated by Django 6.0.1 on 2026-01-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_monitor', '0010_productcsvupload_consider_price_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='skippedpriceimport',
            name='current_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
