# Generated by Django 6.0 on 2026-01-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_productpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypromotion',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat Amount')], max_length=20),
        ),
    ]
