# Generated by Django 6.0.1 on 2026-01-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_csv_upload'),
        ('promotions', '0003_alter_categorypromotion_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypromotion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_promotions', to='catalog.category'),
        ),
    ]
